# Generated by Django 3.1 on 2020-08-22 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievement',
            old_name='challenge_completed',
            new_name='chall_completed',
        ),
        migrations.RenameField(
            model_name='achievement',
            old_name='mountain_completed',
            new_name='mnt_completed',
        ),
    ]
