# Generated by Django 3.1 on 2020-08-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mountain',
            name='challenge',
        ),
        migrations.AddField(
            model_name='challenge',
            name='mountains',
            field=models.ManyToManyField(to='challenges.Mountain'),
        ),
        migrations.AddField(
            model_name='mountain',
            name='distance',
            field=models.IntegerField(default=0),
        ),
    ]
