# Generated by Django 3.1 on 2020-08-17 00:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenges', '0004_auto_20200816_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mountain',
            name='done',
        ),
        migrations.AddField(
            model_name='mountain',
            name='users_completed',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
