# Generated by Django 3.1 on 2020-08-17 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0009_auto_20200817_1214'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Achievement',
        ),
    ]
