# Generated by Django 3.1 on 2020-09-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default='/home/davidpi/Projects/hike-challenge-app/portfolio/static/portfolio/dft.png', upload_to='uploads/'),
        ),
    ]
