# Generated by Django 3.1 on 2020-08-17 16:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenges', '0007_auto_20200817_1200'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Achivement',
            new_name='Achievement',
        ),
    ]
